name: CI
on:
  pull_request:
  push:
jobs:
  build-and-test:
    runs-on: macos-11.0
    strategy:
      matrix:
        xcode-version: [ 12.5.1 ]
        ios-version: [ 14.5 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Select Xcode
        run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode-version }}.app/Contents/Developer'
        
      - name: Bulid and test
        run: |
          set -o pipefail
          xcodebuild \
            -project bowarch-example.xcodeproj \
            -scheme bowarch-example \
            -destination "platform=iOS Simulator,OS=${{ matrix.ios-version }},name=iPhone SE (2nd generation)" \
            -sdk iphonesimulator${{ matrix.ios-version }} \
            -configuration Release | xcpretty -c

